# This is a basic workflow to help you get started with Actions

name: Docs

# Controls when the workflow will run
on: [ push, pull_request ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  docs-build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3.1.2
      - name: Install Mkdocs
        run: pip install mkdocs mkdocs-material

      - name: Build docs
        run: mkdocs build
